import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/service/QueryProvider";
import { Toaster } from "@/components/ui/sonner";
import { ToastContainer } from 'react-toastify';
// import { Button } from "@/components/ui/button";
// import { useLogout } from "@/hooks/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
            {children}
        </QueryProvider>
        <ToastContainer />
        <Toaster />
      </body>
    </html>
  );
}
